config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  # root 'welcome#construction'
  resources :welcome, only: [:index]
  resources :quotes, only: [:create, :new, :index]
  resources :blogs, except: [:show] do 
    collection do 
      get :search
    end
  end
  get "/blogs/:id(.format)" => "blogs#show"

  resources :reviews, except: [:show] do 
    collection do 
      get :search
    end
  end
  
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/dashboard' => 'dashboard#index'

  get "sitemap.xml" => "sitemaps#index", :format => "xml", :as => :sitemap
end

app/models/blog.rb
class Blog < ActiveRecord::Base
  belongs_to :creator, class_name: :User
  belongs_to :updator, class_name: :User

  validates :title, :text, :creator, :updator, :slug, presence: true
  validates :slug, uniqueness: true
  before_validation -> {self.slug = (self.title || '').downcase.gsub(' ', '-').gsub(/[^\w\-]/, '')}

  def self.find_by_slug(slug)
    find_by(slug: slug)
  end

  def self.search(params)
    term = "%#{params[:term].to_s.as_search_param}"
    query = Blog.reorder(id: :desc)

    if params[:term].present?
      query = query.where("title LIKE :term OR text LIKE :term OR tags LIKE :term", term: term)
    end

    return query
  end

  def split_tags
    tags.split(",").reject{|tag| tag.blank?}.map{|tag| tag.strip}
  end
end

app/models/quote.rb
class Quote < ActiveRecord::Base
  validates :name, :phone, :email, presence: true
  attr_accessor :verification
end

app/models/review.rb
class Review < ActiveRecord::Base
  validates :name, :text, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :name, :email, :password_digest, :auth_token, presence: true
  validates :email, :auth_token, uniqueness: true

  before_validation -> {self.auth_token ||= SecureRandom.urlsafe_base64(8)}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find_by(id: session[:user_id], auth_token: session[:auth_token])
  end
  helper_method :current_user

  protected
  def authenticate
    redirect_to '/login' unless current_user
  end

  def get_layout
    current_user ? 'dashboard' : 'application'
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_filter :authenticate, except: [:index, :search, :show]
  layout :get_layout

  def index
    @blogs = Blog.search(params)
  end

  def search
    @blogs = Blog.search(params)
  end

  def new
    @blog = params.has_key?(:blog) ? Blog.new(create_params) : Blog.new
  end

  def create
    @blog = Blog.create(create_params)
    unless @blog.valid?
      render 'new'
      return
    end
    redirect_to blog_path(@blog.slug)
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def update
    @blog = Blog.find(params[:id])
    @blog.update_attributes(update_params)
    unless @blog.valid?
      render 'edit'
      return
    end
    redirect_to blog_path(@blog.slug)
  end

  def show
    @blog = Blog.find_by_slug(params[:id])
  end

  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy
    unless @blog.valid?
      render 'show'
      return
    end
    redirect_to blogs_path, flash: {notice: "Blog destroyed"}
  end

  private
  def instantiate
    @blog = Blog.find params[:id]
  end

  def new_params
    params.require(:blog).permit(:title, :text, :tags)
  end

  def create_params
    params.require(:blog).permit(:title, :text, :tags).merge(creator_id: current_user.id, updator_id: current_user.id)
  end

  def update_params
    params.require(:blog).permit(:title, :text, :tags).merge(updator_id: current_user.id)
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  layout 'dashboard'
  before_filter :authenticate
end

app/controllers/quotes_controller.rb
require 'net/http'
class QuotesController < ApplicationController
  def index
    @quote = Quote.new
    render 'new'
  end

  def new
    @quote = Quote.new
  end

  def create
    @quote = Quote.new(quote_params)
    @quote.errors.add(:verification, " response is incorrect.") if params[:verification].to_s.downcase.strip != "emerald"
    render 'new' and return if @quote.errors.any? || !@quote.save

    RequestMailer.quote(@quote).deliver_now unless Rails.env.development?
    render 'thank_you'
  end

  private
  def quote_params
    return params.require(:quote).permit(:name, :email, :phone, :address, :notes)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_filter :authenticate
  before_filter :instantiate, only: [:edit, :update, :destroy]
  layout :get_layout

  def index
    @reviews = Review.reorder(id: :desc)
  end

  def search
    query = Review.reorder(id: :desc)

    if params[:term]
      term = "%#{params[:term].to_s.as_search_param}"
      query = query.where("name LIKE :term OR text LIKE :term", term: term)
    end

    @reviews = query
  end

  def new
    @review = Review.new
  end

  def create
    @review = Review.create(create_params)

    unless @review.valid?
      render 'new'
      return
    end

    redirect_to reviews_path
  end

  def edit
  end

  def update
    @review.update_attributes(update_params)

    unless @review.valid?
      render 'edit'
      return
    end

    redirect_to reviews_path
  end

  def destroy
    @review.destroy

    unless @review.valid?
      render 'edit'
      return
    end

    redirect_to reviews_path
  end

  private 
  def instantiate
    @review = Review.find params[:id]
  end

  def create_params
    params.require(:review).permit(:name, :text).merge(creator_id: current_user.id, updator_id: current_user.id)
  end

  def update_params
    params.require(:review).permit(:name, :text).merge(updator_id: current_user.id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :authenticate

  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      session[:auth_token] = user.auth_token
      redirect_to '/dashboard'
      return
    end

    redirect_to '/login', flash: {alert: "Wrong username or password."}
  end

  def destroy
    session[:user_id] = nil
    session[:auth_token] = nil
    redirect_to root_path, flash: {notice: "Logged out successfully."}
  end
end

app/controllers/sitemaps_controller.rb
class SitemapsController < ApplicationController
  def index
    respond_to do |format|
      format.xml
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @reviews = Review.all
  end

  def construction
    render layout: "full"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/blogs/_form.html.erb
<%= tinymce_assets %>
<% if @blog.errors.any? %>
  <div class="alert alert-danger">
    <strong>Error!</strong> Could not create blog.
    <% @blog.errors.full_messages.each do |error| %>
      <div><%= error %></div>
    <% end %>
  </div>
<% end %>
<div class="actions"><%= link_to "Back", "/blogs", class: "btn btn-primary" %></div>
<%= form_for @blog do |f| %>
  <div class="form-group">
    <%= f.label :title, 'Title', class: "control-label" %>
    <%= f.text_field :title, class: "form-control", autofocus: true %>
  </div>
  <div class="form-group">
    <%= f.label :text, 'Text', class: "control-label" %>
    <%= f.text_area :text, class: "tinymce", rows: 20 %>
  </div>
  <%= tinymce %>
  <div class="form-group">
    <%= f.label :tags, 'Tags', class: "control-label" %>
    <%= f.text_field :tags, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= submit_tag :Save, class: "btn btn-primary", style: "width: 100%;" %>
  </div>
<% end %>

app/views/blogs/_search_results.html.erb
<% @blogs.each_with_index do |blog, index| %>
  <div class="blog-preview">
    <%= link_to content_tag(:h2, blog.title), blog_path(blog.slug) %>
    <p><%= strip_tags(blog.text) %></p>
    <p class="comment">Added <%= blog.created_at.strftime("%-m/%-d/%Y") %></p>
  </div>
  <% if index < @blogs.size - 1 %>
    <hr>
  <% end %>
<% end %>

app/views/blogs/edit.html.erb
<%= render "form" %>

app/views/blogs/index.html.erb
<div class="container">
  <% if current_user %>
    <div style="margin-bottom: 24px;">
      <%= link_to 'Create Blog', new_blog_path, class: "btn btn-primary" %>
    </div>
  <% end %>
  <%= form_tag search_blogs_path, remote: true, method: :get do %>
    <div class="form-group">
      <%= label_tag :term, 'Search Blogs', class: "control-label" %>
      <div class="input-group">
        <%= text_field_tag :term, params[:term], class: "form-control" %>
        <span class="input-group-btn">
          <%= button_tag content_tag(:span, nil, class: "glyphicon glyphicon-search"), class: "btn btn-primary", type: :submit %>
        </span>
      </div>
    </div>
  <% end %>
  <div id="search_results">
    <%= render "blogs/search_results" %>
  </div>
</div>

app/views/blogs/new.html.erb
<div class="container">
  <%= render "form" %>
</div>

app/views/blogs/show.html.erb
<div class="container">
  <div class="actions">
    <%= link_to "Back", blogs_path, class: "btn btn-primary" %>
    <%= link_to '', edit_blog_path(@blog.id), class: "glyphicon glyphicon-pencil", title: "Edit Blog" if current_user %>    
    <%= link_to '', blog_path(@blog.id), method: :delete, class: "glyphicon glyphicon-trash text-danger", title: "Destroy Blog" if current_user %>    
  </div>
  <div class="blog elevate-z-1">
    <h1 class="blog-title"><%= @blog.title %></h1>
    <p class="blog-date comment">Added <%= @blog.created_at.strftime("%-m/%-d/%Y") %></p>
    <div class="blog-body"><%= @blog.text.html_safe %></div>
    <% if @blog.split_tags.any? %>
      <p class="tags-container">
        <b>Tags:</b> 
        <% @blog.split_tags.each do |tag| %><%= link_to tag, "/blogs?term=#{tag}", class: "btn btn-default" %><% end %></p>
    <% end %>
  </div>
</div>

app/views/dashboard/index.html.erb
<div class="container">
  <h1>Dashboard</h1>
  <h3><%= link_to 'Blogs', blogs_path %></h3>
  <h3><%= link_to 'Reviews', reviews_path %></h3>
</div>

app/views/layouts/_dashboard_header.html.erb
<nav>
  <div class="nav-wrapper">
    <div id="top">
      <div class="container hidden-xs">
        <div class="row">
          <div class="col-lg-3 col-md-3 col-sm-3">
            <%= render "/layouts/logo" %>
          </div>
          <div class="col-lg-9 col-md-9 col-sm-9 menu">
            <div class="menu_wrapper">
              Welcome back, <%= current_user.name %> 
              <%= link_to "Dashboard", '/dashboard' %>
              <%= link_to "Logout", '/logout' %>
            </div>
          </div>
        </div>
      </div>

      <!-- XS -->
      <div class="container visible-xs-block">
        <div class="row">
          <div class="col-xs-2"></div>
          <div class="col-xs-8" style="text-align: center;">
            <%= render "/layouts/logo" %>
          </div>
          <div class="col-xs-2 navbar-collapse-container">
            <%= content_tag :span, nil, class: "glyphicon glyphicon-menu-hamburger", data: {toggle: "collapse", target: "#collapse-menu"}, aria: {expanded: false} %>
          </div>
        </div>
      </div>
    </div>
    <div class="visible-xs-block">
      <div class="collapse navbar-collapse" id="collapse-menu">
        <%= link_to "Dashboard", '/dashboard' %>
        <%= link_to "Logout", '/logout' %>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/_header.html.erb
<nav>
  <div class="nav-wrapper">
    <div id="top">
      <div class="container hidden-xs">
        <div class="row">
          <div class="col-lg-3 col-md-3 col-sm-3">
            <%= render "/layouts/logo" %>
          </div>
          <div class="col-lg-9 col-md-9 col-sm-9 menu">
            <div class="menu_wrapper">
              <%= render "/layouts/links" %>
            </div>
          </div>
        </div>
      </div>

      <!-- XS -->
      <div class="container visible-xs-block">
        <div class="row">
          <div class="col-xs-2"></div>
          <div class="col-xs-8" style="text-align: center;">
            <%= render "/layouts/logo" %>
          </div>
          <div class="col-xs-2 navbar-collapse-container">
            <%= content_tag :span, nil, class: "glyphicon glyphicon-menu-hamburger", data: {toggle: "collapse", target: "#collapse-menu"}, aria: {expanded: false} %>
          </div>
        </div>
      </div>
    </div>
    <div class="visible-xs-block">
      <div class="collapse navbar-collapse" id="collapse-menu">
        <%= render "/layouts/links" %>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/_links.html.erb
<div class="social-media-container">
  <%= link_to image_tag("FB-f-Logo__white_72.png", alt: "Find us on Facebook", title: "Find us on Facebook"), "https://www.facebook.com/EmeraldPestControl/", target: :_blank %>
  <%= link_to image_tag("google.png", alt: "Find reviews on Google", title: "Find Emerald Pest Control reviews on Google"), "https://g.co/kgs/SSt1Oq", target: :_blank, style: "margin-right: 0;" %>
</div>
<%= link_to "request a quote", new_quote_path() %>
<%= link_to "blog", blogs_path() %>
<span class="number">435.619.1633</span>

app/views/layouts/_logo.html.erb
<%= link_to image_tag("emerald-pest-control-logo.png", alt: "Emerald Pest Control - Saint George, Utah", title: "Emerald Pest Control", class: "img-responsive", id: 'logo'), root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <% if @blog %>
  <title><%= @blog.title %></title>
  <meta name="description" content="<%= truncate(strip_tags(@blog.text), length: 100) %>" />
  <meta name="keywords" content="<%= @blog.tags %>" />
  <% else %>
  <title>Emerald Pest Control</title>
  <meta name="keywords" content="emerald pest control, pest control saint george, kill bugs" />
  <meta name="description" content="What's lurking in YOUR walls? Get rid of unwanted pests with the Emerald Pest Control, the best  in Saint George, Utah." />
  <% end %>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= stylesheet_link_tag 'blogs' if params[:controller] == 'blogs' %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1, maximum-scale=1, user-scalable=0" />
  <meta name="author" content="Mark Meacham" />
  <%= favicon_link_tag "favicon.png", type: "image/png" %>
  <script src='https://www.google.com/recaptcha/api.js'></script>
</head>
<body>
<%= render "/layouts/header" %>
<%= yield %>
</body>
</html>

app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Emerald Pest Control</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>

  <%= stylesheet_link_tag params[:controller] %>
  <%= javascript_include_tag params[:controller] %>

  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1, maximum-scale=1, user-scalable=0" />
  <meta name="author" content="Mark Meacham" />
  <%= favicon_link_tag "favicon.png", type: "image/png" %>
</head>
<body>
<%= render "/layouts/dashboard_header" %>
<%= yield %>
</body>
</html>

app/views/quotes/new.html.erb
<div class="container" id="request_a_quote">
  <div class="col-sm-8 col-sm-offset-2 col-xs-12 box">
    <% if @quote.errors.any? %>
      <div class="alert alert-danger">
        <strong>Error!</strong> Could not request quote.
        <% @quote.errors.full_messages.each do |error| %>
          <div><%= error %></div>
        <% end %>
      </div>
    <% end %>
    <%= render "/quotes/form" %>
  </div>
</div>

app/views/quotes/thank_you.html.erb
<h2 style="text-align: center;">Thank you! We will respond to you as soon as we are able.</h2>
<p style="text-align: center;"><%= link_to "Click here to request another quote!", new_quote_path() %></p>

app/views/reviews/_form.html.erb
<%= tinymce_assets %>
<% if @review.errors.any? %>
  <div class="alert alert-danger">
    <strong>Error!</strong> Could not create review.
    <% @review.errors.full_messages.each do |error| %>
      <div><%= error %></div>
    <% end %>
  </div>
<% end %>
<div class="actions">
  <%= link_to "Back", "/reviews", class: "btn btn-primary" %>
  <%= link_to '', review_path(@review.id), method: :delete, class: "glyphicon glyphicon-trash text-danger", title: "Destroy Review" unless @review.new_record? %>    
</div>
<%= form_for @review do |f| %>
  <div class="form-group">
    <%= f.label :name, 'Reviewer Name', class: "control-label" %>
    <%= f.text_field :name, class: "form-control", autofocus: true %>
  </div>
  <div class="form-group">
    <%= f.label :text, 'Text', class: "control-label" %>
    <%= f.text_area :text, class: "tinymce", rows: 20 %>
  </div>
  <%= tinymce %>
  <div class="form-group">
    <%= submit_tag :Save, class: "btn btn-primary", style: "width: 100%;" %>
  </div>
<% end %>

app/views/reviews/_search_results.html.erb
<% @reviews.each_with_index do |review, index| %>
  <div class="review-preview">
    <%= link_to content_tag(:h2, review.name), edit_review_path(review.id) %>
    <p><%= strip_tags(review.text) %></p>
    <p class="comment">Added <%= review.created_at.strftime("%-m/%-d/%Y") %></p>
  </div>
  <% if index < @reviews.size - 1 %>
    <hr>
  <% end %>
<% end %>

app/views/reviews/edit.html.erb
<div class="container">
  <%= render "form" %>
</div>

app/views/reviews/index.html.erb
<div class="container">
  <% if current_user %>
    <div style="margin-bottom: 24px;">
      <%= link_to 'Create Review', new_review_path, class: "btn btn-primary" %>
    </div>
  <% end %>
  <%= form_tag search_reviews_path, remote: true, method: :get do %>
    <div class="form-group">
      <%= label_tag :term, 'Search Reviews', class: "control-label" %>
      <div class="input-group">
        <%= text_field_tag :term, params[:term], class: "form-control" %>
        <span class="input-group-btn">
          <%= button_tag content_tag(:span, nil, class: "glyphicon glyphicon-search"), class: "btn btn-primary", type: :submit %>
        </span>
      </div>
    </div>
  <% end %>
  <div id="search_results">
    <%= render "reviews/search_results" %>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="container-fluid" id="carousel-wrapper">
  <div class="row">
    <div class="col-sm-6 col-xs-6 divider"><div class="divider-bg green-bg"></div></div>
    <div class="col-sm-6 col-xs-6 divider"><div class="divider-bg dark-green-bg"></div></div>
  </div>
  <div class="row">
    <div>
      <div id="slider" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
          <li data-target="#slider" data-slide-to="0" class="active"></li>
          <li data-target="#slider" data-slide-to="1"></li>
          <li data-target="#slider" data-slide-to="2"></li>
          <li data-target="#slider" data-slide-to="3"></li>
        </ol>
        <div class="carousel-inner" role="listbox">
          <div class="item active" id="truck">
            <%= image_tag "emerald-pest-control-truck.jpg", alt: "Emerald Pest Control Truck", title: "Emerald Pest Control Truck", class: 'd-block' %>
          </div>
          <div class="item" id="bug-spray">
            <%= image_tag "bug-spray.jpg", alt: "Bug Spray", class: 'd-block' %>
          </div>
          <div class="item" id="back-of-truck">
            <%= image_tag "back-of-truck.jpg", alt: "Back of Pest Control Truck", class: 'd-block' %>
          </div>
          <div class="item" id="owner">
            <%= image_tag "emerald-pest-owner.jpg", alt: "Brady Barlow - Owner of Emerald Pest Control", title: "Brady Barlow - Owner of Emerald Pest Control in Saint George, Utah", class: 'd-block' %>
          </div>
        </div>
        <a class="carousel-control left" href="#slider" role="button" data-slide="prev">
          <%= content_tag :span, nil, class: "glyphicon glyphicon-chevron-left", "aria-hidden" => true %>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control right" href="#slider" role="button" data-slide="next">
          <%= content_tag :span, nil, class: "glyphicon glyphicon-chevron-right", "aria-hidden" => true %>
          <span class="sr-only">Next</span>
        </a>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-6 col-xs-6 divider"><div class="divider-bg green-bg"></div></div>
    <div class="col-sm-6 col-xs-6 divider"><div class="divider-bg dark-green-bg"></div></div>
  </div>
</div>
<div class="container" style="padding-bottom: 25px;">
  <div class="row">
    <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
      <h1>Emerald Pest Control</h1>
      <p>We use only the highest quality materials available on the market and apply them with state of the art equipment. We provide a 3-point barrier treating 3 feet up and 3 feet out, keeping pests not only out of your home but AWAY from it. We don't cut corners. No diluting. No cheap product. </p>
      <div class='row'>
        <div class="col-lg-4 col-lg-4 col-sm-4 col-xs-12">
          <h2>Safe</h2>
          Everything we apply is organically derived and safe for your family and pets.
        </div>
        <div class="col-lg-4 col-lg-4 col-sm-4 col-xs-12">
          <h2>Effective</h2>
          Only the highest quality products applied with the proper equipment gets the job done right.
        </div>
        <div class="col-lg-4 col-lg-4 col-sm-4 col-xs-12">
          <h2>Resistant</h2>
          Time-released so it wont wear off or become less-effective due to heat or rain.
        </div>
      </div>
      <% if @reviews.any? %>
        <div id="review-slider" class="carousel slide" data-ride="carousel">
          <div class="carousel-inner" role="listbox">
            <% @reviews.each_with_index do |review, index| %>
              <div class="item <%= 'active' if  index == 0 %>" id="<%= review.id %>">
                <div class="carousel-text">
                  <%= review.text.html_safe %>
                  <p class="comment">- <%= review.name %></p>
                </div>
              </div>
            <% end %>
          </div>
          <a class="carousel-control left" href="#review-slider" role="button" data-slide="prev">
            <%= content_tag :span, nil, class: "glyphicon glyphicon-chevron-left", "aria-hidden" => true %>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control right" href="#review-slider" role="button" data-slide="next">
            <%= content_tag :span, nil, class: "glyphicon glyphicon-chevron-right", "aria-hidden" => true %>
            <span class="sr-only">Next</span>
          </a>
        </div>
      <% end %>

      <%= link_to content_tag(:span, "Click here to request a free quote!", class: "btn btn-primary btn-big", style: "margin-top: 25px;"), new_quote_path %>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
      <div id="insects_wrapper">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12"><%= image_tag "ant.png", alt: "Kill Ants" %> Ants</div>
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12"><%= image_tag "cockroach.png", alt: "Kill Cockroaches" %> Cockroaches</div>
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12"><%= image_tag "cricket.png", alt: "Kill Crickets" %> Crickets</div>
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12"><%= image_tag "rodent.png", alt: "Kill Rodents" %> Rodents</div>
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12"><%= image_tag "scorpion.png", alt: "Kill Scorpions" %> Scorpions</div>
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12"><%= image_tag "kill-spider.png", alt: "Kill Spiders" %> Spiders</div>
      </div>
    </div>
  </div>
</div>

<div class="parallax power-spray">
  <div class="caption">
    <div class="border"><h2>POWER-SPRAY</h2></div>
  </div>
</div>
<div class="container">
  <p class="description">By applying our spray to the exterior of your home using our premium power-spray equipment we are able to not only treat the pests you see, but the ones you don’t. The micro-encapsulated spray is time released and soaks into the ground reaching pests where they live and breed, killing off the nests completely and preventing them from relocating. </p>
</div>

<div class="parallax granules">
  <div class="caption">
    <div class="border"><h2>GRANULES</h2></div>
  </div>
</div>
<div class="container">
  <p class="description">By applying granules to the yard, we are able to treat the pests that are not only nesting near the base of the house, but actually IN the grass and yard. We granulate up to 20 feet at EVERY SERVICE using our premium waterproof and SAFE granules.</p>
</div>

<div class="parallax dust-injection">
  <div class="caption">
    <div class="border"><h2>DUST-INJECTIONS</h2></div>
  </div>
</div>
<div class="container">
  <p class="description">Many pests, including scorpions and black widows, nest inside walls both inside and outside where it is cool in the summer and warm in the winter. Rather than leaving these unseen and dangerous pests alone, we provide an extra service that specifically targets these areas. Our dust quickly spreads to even the smallest spaces inside block walls and power outlets where liquids can’t, killing any unwanted pests and preventing them from returning.</p>
</div>

<div class="parallax house">
  <div class="caption">
    <div class="border"><h2>360 INTERIOR + GARAGE</h2></div>
  </div>
</div>
<div class="container">
  <p class="description">At Emerald Pest Control, family and safety are our top priorities. We use only the safest, not the cheapest, products. We mix with precise measurements and do not dilute - keeping your family and pets SAFE and you PEST FREE. Our interior service treats with pinpoint accuracy 360 degrees surrounding the entire interior of the house AND garage.</p>
</div>

<div class="parallax de-web">
  <div class="caption">
    <div class="border"><h2>DE-WEB</h2></div>
  </div>
</div>
<div class="container">
  <p class="description">While treating pests inside and out is key, we also treat pests living ON your home. Every visit we provide FREE web and nest knockdown near the highest and lowest points. These nests and webs often contain pests and egg sacks that haven't yet hatched. Our equipment can reach up to three stories high to ensure the removal of all webs and nests.</p>
</div>

<div class="parallax emerald-promise">
  <div class="caption">
    <div class="border"><h2>THE EMERALD PROMISE</h2></div>
  </div>
</div>
<div class="container">
  <p class="description">If at any time you find an unwanted pest, we will be out immediately FREE OF CHARGE to remove them, inspect, and provide an extra barrier.</p>
</div>

<footer>
  Emerald Pest Control in Saint George, Utah - Call us today at <span class="number">435.619.1633</span> or <%= link_to "Click here to request a quote!", new_quote_path %>
</footer>